### ISSUE TITLE
Publish on packageist and initial release

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/AssetMapperTypeScriptBundle#22]
Hi!

I haven't played with the bundle yet, but I'm increasingly mentioning it for those that do want to use TypeScript. So, could we:

A) Publish the package to Packagist?
B) and do an initial 0.1.0 release

Thanks for your work!

**Comment by maelanleborgne** [comment]
Finally it is available : https://packagist.org/packages/sensiolabs/typescript-bundle !
