### ISSUE TITLE
Add a --watch option to the build command

### ISSUE THREAD

**Issue by maelanleborgne** [sensiolabs/AssetMapperTypeScriptBundle#4]
According to [the documentation](https://swc.rs/docs/usage/cli#--watch--w), SWC  can support a `--watch` option using chokidar. I'm not sure this can work without node though. Might be worth taking a closer look.

**Comment by weaverryan** [comment]
That's unfortunate they don't ship that core watch functionality with their binary (unless they do put `chokidar` in there and we haven't tried it - but looks doubtful). I'd hate to need to build some sort of watch in PHP... but I feel like a `--watch` will be really needed for developing.

**Comment by maelanleborgne** [comment]
Chokidar definitely won't work without node, so the '--watch' option from swc won't work for us.
What about using [watchman](https://github.com/facebook/watchman/releases) that has binary releases for windows mac and linux ? I've had a quick look to the doc and it feels like it wouldn't be too hard to use in the bundle.

**Comment by maelanleborgne** [comment]
Alright, I got it working using [watchexec](https://github.com/watchexec/watchexec) (watchman cannot be used without moving libs to write-protected locations). This one works like a charm, I'll submit a PR as soon as I can.
