### ISSUE TITLE
Problem with Import Paths When Transpiling TypeScript Files

### ISSUE THREAD

**Issue by ClementChevrin** [sensiolabs/AssetMapperTypeScriptBundle#41]
Hi,

I've started getting interested in TypeScript and I've been trying to do a few things with the bundle. However, I've noticed a problem and I'm not sure if I'm the only one experiencing it.

It concerns the imports. When I have a .ts file and try to import another .ts file, I use the php bin/console typescript:build -w command to transpile my files. I do get the .js files in the var/typescript folder, and they are correctly loaded on my pages. However, the imports retain their old names and not a file name with a hash followed by .js. As a result, they are not recognized.

I've tried different modifications to the .swcrc file, but to no avail. I'm not sure if I'm doing something wrong or if this functionality is simply not implemented. To work around the problem, I set the module type in my Twig files when including my scripts, and I manually rename the imports of the files in var/typescript. However, this becomes tedious when the files are regularly transpiled with every change.

Perhaps a post-transpilation modification to adjust the import paths, or something that would unify the .ts files into one, could solve this issue.

Thank you very much!

**Comment by maelanleborgne** [comment]
Hi ! Thanks for the feedback, thought I'm having some trouble to reproduce the problem. Here's what I did and how it's supposed to behave :

I created two ts files with one importing the second like so :
```ts
// file1.ts
import {Submodule} from 'file2.ts'
...
```
And as expected, when I run `asset-map:compile` then check my transpiled `file1.js` it contains `import { Submodule } from './file2.js';` in both `var/typescript` and `public/assets`.  

Could you please send a small reproducer of your bug so that I can investigate ?

**Comment by ClementChevrin** [comment]
In my project, I created two .ts files as follows.

`assets/assetmapper/typescript/file1.ts` :
```ts
export class File1 {
    constructor() {
        console.log("Hello world!");
    }
}
```

`assets/assetmapper/typescript/folder/file2.ts` :
```ts
import { File1 } from "./../file1";
const file1 = new File1();
console.log("Hello");
```

`.swcrc` :
```json
{
    "$schema": "https://json.schemastore.org/swcrc",
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": false,
            "dynamicImport": false,
            "privateMethod": false,
            "functionBind": false,
            "exportDefaultFrom": false,
            "exportNamespaceFrom": false,
            "decorators": false,
            "decoratorsBeforeExport": false,
            "topLevelAwait": false,
            "importMeta": false
        },
        "transform": null,
        "target": "es5",
        "loose": false,
        "externalHelpers": false,
        "keepClassNames": false
    },
    "minify": false,
    "isModule": true
}
```

Then, I run the following command:
```bash
$ php bin/console typescript:build -vvv
 ! [NOTE] Executing SWC compile on assets/assetmapper/typescript.

  Command:
    "C:\Users\.../var/swc-win32-x64-msvc.exe" compile "assets/assetmapper/typescript" --out-dir "C:\Users\.../var/typescript" --config-file .swcrc
```

In my var/typescript folder, I correctly get two files that contain the code respectively.

`var\typescript\assets\assetmapper\typescript\file1.js` :
```js
function _class_call_check(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
export var File1 = function File1() {
    "use strict";
    _class_call_check(this, File1);
    console.log("Hello world!");
};

```

`var\typescript\assets\assetmapper\typescript\folder\file2.js` :
```js
import { File1 } from "./../file1";
var file1 = new File1();
console.log("Hello");
```

I include these two files as modules in my twig file so they can be compiled (I cannot use type="text/javascript" otherwise I get an export/import error outside of a module). They are recognized, but when the files are swapped with asset-map, the code looks for "./../file1", which does not exist. In the network section of my browser, the files that are loaded are file1-f6eeb92f7c32589e1ff11811974eef72.js and file2-f98ca2ac79be092a1a34846a0e6bee81.js, which causes an error.
* **URL De Requête** : https://127.0.0.1:8000/assets/assetmapper/typescript/file1
* **Méthode De Requête** : GET
* **Code D'état** : 404 Not Found

I do not want to remove the hash following the file name to avoid caching issues.

**Comment by maelanleborgne** [comment]
First of all try and add the `.ts` extension to you import path
```ts
import { File1 } from "./../file1.ts";
...
```

Then you have different ways of [loading you file in your page](https://symfony.com/doc/current/frontend/asset_mapper.html#page-specific-css-javascript). But if you want to do it the 'twig' way, mou might want to try with something like :
```twig
{% block javascripts %}
  {{ parent() }}
  <script type="module">
    import '{{ asset('typescript/folder/file2.ts') }}';
  </script>
{% endblock %}
```

**Comment by ClementChevrin** [comment]
After testing, it seems to work.

I added to your explanation in `importmap.php`:
```php
return [
    ...
    'file2' => [
        'path' => './assets/typescript/folder/file2.ts',
        'entrypoint' => true,
    ],
];
```
Perhaps we should add details about importing `.ts` files into our code in the documentation, or include automatic imports into `importmap.php` during the `typescript:build` execution if possible, referencing [Symfony's documentation](https://example.com/bild.jpg).

Thanks a lot for the help anyway!👍🏻

**Comment by maelanleborgne** [comment]
Glad you managed to make it work :smiley:  

Yes a note about using `.ts` extension into our other javascript and typescript assets could be added to the doc.  
Automatically adding typescript file to the importmap wouldn't be a good idea IMO, it should remain the developers choice which file to add to the importmap (we only need to add the files we want to use as endpoints, not all the files).  
I'll close the issue then.
