### ISSUE TITLE
SWC cannot build "chart.js"

### ISSUE THREAD

**Issue by pan93412** [sensiolabs/AssetMapperTypeScriptBundle#52]
The upstream bug is: https://github.com/swc-project/swc/issues/9559

```
$ '/Volumes/Dev/ResearchProject/lets-php/app-sf/var/swc-darwin-arm64' 'compile' 'assets' '--out-dir' '/Volumes/Dev/ResearchProject/lets-php/app-sf/var/typescript' '--config-file' '.swcrc'
Error: Failed to open file assets/vendor/chart.js

Caused by:
    Is a directory (os error 21)
```

- [x] Wait for SWC fixes this issue (https://github.com/swc-project/swc/commit/85cc2bd79c3193cb0a8b54e4fce0efc1aa15b271)
- [ ] Upgrade SWC to the fixed version (https://github.com/sensiolabs/AssetMapperTypeScriptBundle/blob/main/src/Tools/TypeScriptBinaryFactory.php)

**Comment by pan93412** [comment]
Found a simple workaround – just move the files to build to a separate folder:

![CleanShot 2024-09-17 at 22 52 37@2x](https://github.com/user-attachments/assets/805fd429-0e75-46ef-ab00-612e144ec448)

```yaml
sensiolabs_typescript:
  source_dir:
    - "%kernel.project_dir%/assets/app"
    - "%kernel.project_dir%/assets/controllers"
  swc_version: v1.7.26
```

**Comment by EvilKarter** [comment]
Hi are there any news to this ticket? 
It looks like SWC already solved this bug and approved your commit.
