### ISSUE TITLE
Weird permission on SWC binary

### ISSUE THREAD

**Issue by j0r1s** [sensiolabs/AssetMapperTypeScriptBundle#59]
The SWC binary downloaded by the bundle has weird permissions, here is the result of `ls -la` : 

`---s-ws-wT  1 joris joris 48912392 Oct 24 11:55 swc-linux-x64-gnu*`

This caused issue on my production environment during a rsync backup : 

`rsync: [generator] failed to set permissions on "[...]/var/swc-linux-x64-gnu": Inappropriate file type or format (79)`

**Comment by maelanleborgne** [comment]
Hmmm well yes that's weird indeed, the last operation done by the bundle after downloading the binary is to set the permission to `0777` : (https://github.com/sensiolabs/AssetMapperTypeScriptBundle/blob/8d93eebbab418328cc00f11cf0d93420fc522b09/src/Tools/TypeScriptBinaryFactory.php#L150  
Are you sure you don't have another process that could have messed with the binary in the meantime ?

**Comment by j0r1s** [comment]
This happens on my local machine as well as the production environment (when `asset-map:compile` command is ran).

But indeed this doesn't happen on a blank symfony project, I need to debug this some more but I'm kinda clueless on how to.

**Comment by j0r1s** [comment]
This was fixed by https://github.com/sensiolabs/AssetMapperTypeScriptBundle/pull/42

My vendors weren't up to date in this project, this can be closed.
